version: '3'

services:

  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: <yourpassword>
      POSTGRES_DB: netflix
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"